[dotnet]
sdk-version = "8.0"

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish --no-restore -c Release -o /app/out project-redcode.csproj"
]

[start]
cmd = "dotnet /app/out/project-redcode.dll"