[phases]
install = "dotnet restore"
build = "dotnet publish -c Release -o /app/out"

[start]
cmd = "dotnet /app/out/project-redcode.dll"

[variables]
DOTNET_SDK_VERSION = "8.0"

[dotnet]
sdk-version = "8.0"